--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nicholass003/VersionCommand
build-by-default: true
branches:
- main
projects:
  VersionCommand:
    path: ""
    icon: "assets/icon.png"
...
